name: Deploy Bokeh App

on:
  push:
    branches:
      - master  # Triggers on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt      

      - name: Deploy to Render/Railway
        run: |
          # Command to deploy your app, example for Render:
          bokeh serve --show main.py            

